# ??debug???????????????????
debug: true

# root?????debug????debug??????springboot???
# root??????debug
# ???????root????????????????
logging:
  # ???????????
  group:
     ebank: ?1,??,??
     iservice: com.alibaba
  level:
    # root?????????
    root: debug
    # ??????????
    ??: ????
    # ??????????
    ebank: warn

  pattern:
    console: "%d - %m%n"
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 5KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
